model:
  base_learning_rate: 1.0e-05
  target: modules.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    log_every_t: 100
    timesteps: 1000
    loss_type: l2
    first_stage_key: image
    cs_stage_key: image
    image_size: 64
    channels: 3
    concat_mode: true
    cond_stage_trainable: true
    monitor: val/loss
    scheduler_config:
      target: modules.lr_scheduler.LambdaWarmUpCosineScheduler
      params:
        verbosity_interval: 0
        warm_up_steps: 5000
        max_decay_steps: 100000
        lr_start: 0.001
        lr_max: 0.1
        lr_min: 0.0001
    unet_config:
      target: modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 8
        out_channels: 3
        model_channels: 160
        attention_resolutions:
        - 16
        - 8
        # - 4
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 8
        num_head_channels: 32
    first_stage_config:
      target: modules.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        monitor: val/rec_loss
        ckpt_path: models/first_stage_models/vq-f4/model.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cs_stage_config:
      target: modules.csmodels.CSNET
      params:
        sr: 0.1
        block_size: 32
        in_channels: 3
        out_channels: 5

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 24
    num_workers: 12
    wrap: false
    train:
      target: modules.data.custom.CustomTrain
      params:
        training_images_list_file: ../datasets/FULL3/train.txt
        size: 256
    validation:
      target: modules.data.custom.CustomTest
      params:
        test_images_list_file: ../datasets/FULL3/val.txt
        size: 256

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000
        max_images: 4
        increase_log_steps: False

  trainer:
    benchmark: True